create table TAB_USER
(
   USER_ID              bigint(20) not null auto_increment comment '用户标识',
   USER_NAME            varchar(256) comment '用户名称',
   GENDER               varchar(2) comment '性别',
   AVATAR_NAME          varchar(256) comment '头像地址',
   AVATAR_PATH          varchar(256) comment '头像真实路径',
   EMAIL                varchar(256) comment '邮箱',
   LINK_PHONE           varchar(256) comment '手机号码',
   PASSWORD             varchar(256) comment '密码',
   ADMIN_FLAG           int(1) comment '是否为ADMIN账号',
   ENABLED_FLAG         int(1) comment '状态：1启用、0禁用',
   PWD_RESET_TIME       varchar(2) comment '修改密码的时间',
   VALID_DATE           datetime comment '生效日期',
   EXPIRE_DATE          datetime comment '失效日期',
   DATA_STATUS          varchar(8) comment '数据状态',
   CREATE_DATE          datetime comment '创建日期',
   CREATE_OP_ID         varchar(32) comment '创建操作员编码',
   CREATE_ORG_ID        varchar(32) comment '创建组织编码',
   DONE_DATE            datetime comment '操作日期',
   OP_ID                varchar(32) comment '操作员编码',
   ORG_ID               varchar(32) comment '操作组织编码',
   MGMT_DISTRICT        varchar(8) comment '管理地区',
   MGMT_COUNTY          varchar(8) comment '管理县市',
   REGION_ID            varchar(8) comment '数据归属地区',
   TENANT_CODE          varchar(32) comment '租户编码',
   primary key (USER_ID)
);
